Repository Next-Room/NextRoom-be, pull requests merged in 2023-08, with the labels that each got.

#59 [REFACTOR] Login 성공 응답에 shopName 추가
  src/main/java/com/nextroom/oescape/dto/AuthDto.java
  src/main/java/com/nextroom/oescape/dto/TokenDto.java
  src/main/java/com/nextroom/oescape/repository/ShopRepository.java
  src/main/java/com/nextroom/oescape/service/AuthService.java
Labels: ♻️refactor

#53 [FIX] Security 로직 내 예외 처리 구현
  src/main/java/com/nextroom/oescape/exceptions/GlobalExceptionHandler.java
  src/main/java/com/nextroom/oescape/exceptions/StatusCode.java
  src/main/java/com/nextroom/oescape/security/ExceptionHandlerFilter.java
  src/main/java/com/nextroom/oescape/security/SecurityUtil.java
  src/main/java/com/nextroom/oescape/security/TokenProvider.java
  src/main/java/com/nextroom/oescape/security/config/SecurityConfig.java
  src/main/java/com/nextroom/oescape/service/AuthService.java
Labels: ✨feature, 🔨fix, ♻️refactor

#61 [HOTFIX] 토큰 검증 관련 에러 시 잘못된 응답 코드 수정
  src/main/java/com/nextroom/oescape/security/ExceptionHandlerFilter.java
Labels: 🔨fix

#62 jenkins 설정을 위한 main 업데이트
  .github/workflows/deploy.yml
  .gitignore
  README.md
  appspec.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  scripts/start.sh
  scripts/stop.sh
  settings.gradle
  src/main/java/com/nextroom/oescape/OEscapeApplication.java
  src/main/java/com/nextroom/oescape/config/SwaggerConfig.java
  src/main/java/com/nextroom/oescape/controller/AuthController.java
  src/main/java/com/nextroom/oescape/controller/HintController.java
  src/main/java/com/nextroom/oescape/controller/TestController.java
  src/main/java/com/nextroom/oescape/controller/ThemeController.java
  src/main/java/com/nextroom/oescape/domain/Authority.java
  src/main/java/com/nextroom/oescape/domain/Hint.java
  src/main/java/com/nextroom/oescape/domain/RefreshToken.java
  src/main/java/com/nextroom/oescape/domain/Shop.java
  src/main/java/com/nextroom/oescape/domain/Theme.java
  src/main/java/com/nextroom/oescape/dto/AuthDto.java
  src/main/java/com/nextroom/oescape/dto/BaseResponse.java
  src/main/java/com/nextroom/oescape/dto/DataResponse.java
  src/main/java/com/nextroom/oescape/dto/HintDto.java
  src/main/java/com/nextroom/oescape/dto/ThemeDto.java
  src/main/java/com/nextroom/oescape/dto/TokenDto.java
  src/main/java/com/nextroom/oescape/exceptions/CustomException.java
  src/main/java/com/nextroom/oescape/exceptions/ErrorResponse.java
  src/main/java/com/nextroom/oescape/exceptions/GlobalExceptionHandler.java
  src/main/java/com/nextroom/oescape/exceptions/StatusCode.java
  src/main/java/com/nextroom/oescape/repository/HintRepository.java
  src/main/java/com/nextroom/oescape/repository/RefreshTokenRepository.java
  src/main/java/com/nextroom/oescape/repository/ShopRepository.java
  src/main/java/com/nextroom/oescape/repository/ThemeRepository.java
  src/main/java/com/nextroom/oescape/security/ExceptionHandlerFilter.java
  src/main/java/com/nextroom/oescape/security/SecurityUtil.java
  src/main/java/com/nextroom/oescape/security/TokenProvider.java
  src/main/java/com/nextroom/oescape/security/config/JwtSecurityConfig.java
  src/main/java/com/nextroom/oescape/security/config/SecurityConfig.java
  src/main/java/com/nextroom/oescape/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/nextroom/oescape/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/nextroom/oescape/security/jwt/JwtFilter.java
  src/main/java/com/nextroom/oescape/service/AuthService.java
  src/main/java/com/nextroom/oescape/service/CustomUserDetailsService.java
  src/main/java/com/nextroom/oescape/service/HintService.java
  src/main/java/com/nextroom/oescape/service/ThemeService.java
  src/main/java/com/nextroom/oescape/util/Timestamped.java
  src/main/java/com/todayescape/TodayEscapeApplication.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/test/java/com/nextroom/oescape/OEscapeApplicationTests.java
  src/test/java/com/nextroom/oescape/controller/ThemeControllerTest.java
  src/test/java/com/nextroom/oescape/domain/ThemeTest.java
  src/test/java/com/nextroom/oescape/repository/ThemeRepositoryTest.java
  src/test/java/com/nextroom/oescape/service/ThemeServiceTest.java
Labels: ✨feature

#66 [REFACTOR] Swagger profile 설정
  src/main/java/com/nextroom/oescape/config/SwaggerConfig.java
Labels: ♻️refactor

#68 [REFACTOR] Swagger profile 설정 main 업데이트
  scripts/start.sh
  src/main/java/com/nextroom/oescape/config/SwaggerConfig.java
Labels: ♻️refactor

#69 [HOTFIX] 로그인 실패 시 빈 200 에러 수정
  src/main/java/com/nextroom/nextRoomServer/exceptions/GlobalExceptionHandler.java
  src/main/java/com/nextroom/nextRoomServer/exceptions/StatusCode.java
  src/main/java/com/nextroom/nextRoomServer/security/jwt/JwtFilter.java
Labels: 🔨fix
