Repository Next-Room/NextRoom-be, pull requests merged in 2023-07, with the labels that each got.

#5 Feature: initial setting
  build.gradle
  src/main/java/com/todayescape/config/SwaggerConfig.java
  src/main/java/com/todayescape/controller/TestController.java
  src/main/java/com/todayescape/domain/Hint.java
  src/main/java/com/todayescape/domain/Shop.java
  src/main/java/com/todayescape/domain/Theme.java
  src/main/java/com/todayescape/dto/BaseResponse.java
  src/main/java/com/todayescape/dto/DataResponse.java
  src/main/java/com/todayescape/exceptions/CustomException.java
  src/main/java/com/todayescape/exceptions/ErrorResponse.java
  src/main/java/com/todayescape/exceptions/GlobalExceptionHandler.java
  src/main/java/com/todayescape/exceptions/StatusCode.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨feature

#10 Hotfix: h2 console access (#6)
  src/main/java/com/todayescape/config/SecurityConfig.java
Labels: 🐞bug, ✨feature

#9 Refactor: 프로젝트/패키지명 변경 (#8)
  README.md
  settings.gradle
  src/main/java/com/nextroom/oescape/OEscapeApplication.java
  src/main/java/com/nextroom/oescape/config/SwaggerConfig.java
  src/main/java/com/nextroom/oescape/controller/TestController.java
  src/main/java/com/nextroom/oescape/domain/Hint.java
  src/main/java/com/nextroom/oescape/domain/Shop.java
  src/main/java/com/nextroom/oescape/domain/Theme.java
  src/main/java/com/nextroom/oescape/dto/BaseResponse.java
  src/main/java/com/nextroom/oescape/dto/DataResponse.java
  src/main/java/com/nextroom/oescape/exceptions/CustomException.java
  src/main/java/com/nextroom/oescape/exceptions/ErrorResponse.java
  src/main/java/com/nextroom/oescape/exceptions/GlobalExceptionHandler.java
  src/main/java/com/nextroom/oescape/exceptions/StatusCode.java
  src/test/java/com/nextroom/oescape/OEscapeApplicationTests.java
Labels: ♻️refactor

#12 Refactor: security config 파일 패키지 변경
  src/main/java/com/nextroom/oescape/config/SecurityConfig.java
Labels: ♻️refactor

#14 [FEAT] 배포를 위한 스크림트, 설정 파일 작성
  appspec.yml
  build.gradle
  scripts/start.sh
  scripts/stop.sh
Labels: ✨feature

#15 [FIX] UNIX 권한 이슈 수정
  gradlew
Labels: 🔨fix

#16 [FIX] gradle-wrapper.jar 파일 ignore 해제
  .gitignore
  gradle/wrapper/gradle-wrapper.jar
Labels: 🔨fix

#17 [FEAT] Theme 테스트코드 작성 및 API 구현
  build.gradle
  src/main/java/com/nextroom/oescape/OEscapeApplication.java
  src/main/java/com/nextroom/oescape/config/SwaggerConfig.java
  src/main/java/com/nextroom/oescape/controller/TestController.java
  src/main/java/com/nextroom/oescape/controller/ThemeController.java
  src/main/java/com/nextroom/oescape/domain/Theme.java
  src/main/java/com/nextroom/oescape/dto/ThemeDto.java
  src/main/java/com/nextroom/oescape/exceptions/StatusCode.java
  src/main/java/com/nextroom/oescape/repository/ThemeRepository.java
  src/main/java/com/nextroom/oescape/service/ThemeService.java
  src/test/java/com/nextroom/oescape/controller/ThemeControllerTest.java
  src/test/java/com/nextroom/oescape/domain/ThemeTest.java
  src/test/java/com/nextroom/oescape/repository/ThemeRepositoryTest.java
  src/test/java/com/nextroom/oescape/service/ThemeServiceTest.java
Labels: ✨feature

#21 [FEAT] 배포를 위한 RDS 연결 정보 입력 프로세스 구현
  .github/workflows/deploy.yml
Labels: ✨feature

#22 [FEAT] Theme API 구현
  src/main/java/com/nextroom/oescape/controller/ThemeController.java
  src/main/java/com/nextroom/oescape/domain/Theme.java
  src/main/java/com/nextroom/oescape/exceptions/StatusCode.java
  src/main/java/com/nextroom/oescape/repository/ThemeRepository.java
  src/main/java/com/nextroom/oescape/service/ThemeService.java
  src/test/java/com/nextroom/oescape/service/ThemeServiceTest.java
Labels: ✨feature

#24 Feature: 업체 로그인/회원가입 구현
  build.gradle
  src/main/java/com/nextroom/oescape/config/SecurityConfig.java
  src/main/java/com/nextroom/oescape/controller/AuthController.java
  src/main/java/com/nextroom/oescape/controller/ThemeController.java
  src/main/java/com/nextroom/oescape/domain/Authority.java
  src/main/java/com/nextroom/oescape/domain/RefreshToken.java
  src/main/java/com/nextroom/oescape/domain/Shop.java
  src/main/java/com/nextroom/oescape/dto/AuthDto.java
  src/main/java/com/nextroom/oescape/dto/ThemeDto.java
  src/main/java/com/nextroom/oescape/dto/TokenDto.java
  src/main/java/com/nextroom/oescape/exceptions/StatusCode.java
  src/main/java/com/nextroom/oescape/repository/RefreshTokenRepository.java
  src/main/java/com/nextroom/oescape/repository/ShopRepository.java
  src/main/java/com/nextroom/oescape/security/SecurityUtil.java
  src/main/java/com/nextroom/oescape/security/TokenProvider.java
  src/main/java/com/nextroom/oescape/security/config/JwtSecurityConfig.java
  src/main/java/com/nextroom/oescape/security/config/SecurityConfig.java
  src/main/java/com/nextroom/oescape/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/nextroom/oescape/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/nextroom/oescape/security/jwt/JwtFilter.java
  src/main/java/com/nextroom/oescape/service/AuthService.java
  src/main/java/com/nextroom/oescape/service/CustomUserDetailsService.java
  src/main/java/com/nextroom/oescape/service/ThemeService.java
Labels: ✨feature, 🔨fix, ♻️refactor

#26 [FEAT] cors 설정 추가
  src/main/java/com/nextroom/oescape/security/config/SecurityConfig.java
Labels: ✨feature, 🔨fix

#27 [FEAT] 힌트 API 구현
  src/main/java/com/nextroom/oescape/controller/HintController.java
  src/main/java/com/nextroom/oescape/domain/Hint.java
  src/main/java/com/nextroom/oescape/domain/Shop.java
  src/main/java/com/nextroom/oescape/domain/Theme.java
  src/main/java/com/nextroom/oescape/dto/HintDto.java
  src/main/java/com/nextroom/oescape/exceptions/StatusCode.java
  src/main/java/com/nextroom/oescape/repository/HintRepository.java
  src/main/java/com/nextroom/oescape/repository/ThemeRepository.java
  src/main/java/com/nextroom/oescape/service/HintService.java
Labels: ✨feature

#28 [FIX] SignUpRequestDto 객체 생성이 안되던 문제 해결
  src/main/java/com/nextroom/oescape/dto/AuthDto.java
  src/main/java/com/nextroom/oescape/service/AuthService.java
Labels: 🐞bug, 🔨fix

#29 [REFACTOR] Controller에 Swqgger 어노테이션 추가
  src/main/java/com/nextroom/oescape/controller/AuthController.java
  src/main/java/com/nextroom/oescape/controller/HintController.java
  src/main/java/com/nextroom/oescape/controller/ThemeController.java
  src/main/java/com/nextroom/oescape/dto/HintDto.java
  src/main/java/com/nextroom/oescape/security/config/SecurityConfig.java
Labels: ♻️refactor

#30 [FEAT] hint/theme api 내 shop 검증 로직 구현
  src/main/java/com/nextroom/oescape/controller/AuthController.java
  src/main/java/com/nextroom/oescape/controller/HintController.java
  src/main/java/com/nextroom/oescape/controller/ThemeController.java
  src/main/java/com/nextroom/oescape/exceptions/StatusCode.java
  src/main/java/com/nextroom/oescape/security/SecurityUtil.java
  src/main/java/com/nextroom/oescape/service/HintService.java
  src/main/java/com/nextroom/oescape/service/ThemeService.java
Labels: 🐞bug, ✨feature

#31 [FIX] android 인증 면제
  src/main/java/com/nextroom/oescape/controller/ThemeController.java
  src/main/java/com/nextroom/oescape/exceptions/StatusCode.java
  src/main/java/com/nextroom/oescape/security/config/SecurityConfig.java
  src/main/java/com/nextroom/oescape/service/ThemeService.java
Labels: ✨feature, 🔨fix

#37 [REFACTOR] findById 적용 및 NOTFOUND 핸들링 구현 (#36)
  src/main/java/com/nextroom/oescape/service/HintService.java
Labels: ♻️refactor

#38 [REFACTOR] Auth 도메인 예외 처리 강화 (#34)
  build.gradle
  src/main/java/com/nextroom/oescape/controller/AuthController.java
  src/main/java/com/nextroom/oescape/dto/AuthDto.java
  src/main/java/com/nextroom/oescape/exceptions/GlobalExceptionHandler.java
  src/main/java/com/nextroom/oescape/service/AuthService.java
Labels: ✨feature, ♻️refactor

#42 [CHORE] requireNonNull 중첩 사용 삭제
  src/main/java/com/nextroom/oescape/exceptions/GlobalExceptionHandler.java
Labels: ♻️refactor

#43 [REFACTOR] Theme 예외 처리 강화
  src/main/java/com/nextroom/oescape/controller/ThemeController.java
  src/main/java/com/nextroom/oescape/domain/Theme.java
  src/main/java/com/nextroom/oescape/dto/ThemeDto.java
  src/main/java/com/nextroom/oescape/service/ThemeService.java
Labels: ♻️refactor

#44 [REFACTOR] 힌트 예외 처리 강화
  src/main/java/com/nextroom/oescape/controller/HintController.java
  src/main/java/com/nextroom/oescape/dto/HintDto.java
  src/main/java/com/nextroom/oescape/exceptions/GlobalExceptionHandler.java
  src/main/java/com/nextroom/oescape/exceptions/StatusCode.java
  src/main/java/com/nextroom/oescape/repository/HintRepository.java
  src/main/java/com/nextroom/oescape/service/HintService.java
Labels: ✨feature, ♻️refactor

#45 [FEAT] Database Column 추가 및 삭제
  src/main/java/com/nextroom/oescape/OEscapeApplication.java
  src/main/java/com/nextroom/oescape/domain/Hint.java
  src/main/java/com/nextroom/oescape/domain/Shop.java
  src/main/java/com/nextroom/oescape/domain/Theme.java
  src/main/java/com/nextroom/oescape/dto/AuthDto.java
  src/main/java/com/nextroom/oescape/dto/HintDto.java
  src/main/java/com/nextroom/oescape/dto/ThemeDto.java
  src/main/java/com/nextroom/oescape/service/AuthService.java
  src/main/java/com/nextroom/oescape/service/HintService.java
  src/main/java/com/nextroom/oescape/service/ThemeService.java
  src/main/java/com/nextroom/oescape/util/Timestamped.java
Labels: ✨feature

#56 [REFACTOR] DTO 변환 메서드 구현
  src/main/java/com/nextroom/oescape/domain/Hint.java
  src/main/java/com/nextroom/oescape/dto/HintDto.java
  src/main/java/com/nextroom/oescape/dto/ThemeDto.java
  src/main/java/com/nextroom/oescape/service/HintService.java
  src/main/java/com/nextroom/oescape/service/ThemeService.java
Labels: ♻️refactor

#51 [FEAT] 패스워드 로직 구현
  src/main/java/com/nextroom/oescape/controller/AuthController.java
  src/main/java/com/nextroom/oescape/dto/AuthDto.java
Labels: ✨feature

#54 [FEAT] 엔티티 클래스 column 조건 설정
  src/main/java/com/nextroom/oescape/domain/Hint.java
  src/main/java/com/nextroom/oescape/domain/Shop.java
  src/main/java/com/nextroom/oescape/domain/Theme.java
Labels: ✨feature
