Repository Next-Room/NextRoom-be, pull requests merged in 2024-11, with the labels that each got.

#142 [FEAT] Environment 검증 로직 추가
  src/main/java/com/nextroom/nextRoomServer/dto/SubscriptionDto.java
  src/main/java/com/nextroom/nextRoomServer/exceptions/StatusCode.java
  src/main/java/com/nextroom/nextRoomServer/util/inapp/AndroidPurchaseUtils.java
Labels: ✨feature, 🔨fix

#144 [FEAT] Logback 추가
  src/main/java/com/nextroom/nextRoomServer/controller/PaymentController.java
  src/main/java/com/nextroom/nextRoomServer/dto/SubscriptionDto.java
  src/main/java/com/nextroom/nextRoomServer/service/PaymentService.java
  src/main/java/com/nextroom/nextRoomServer/service/SubscriptionService.java
  src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java
  src/main/java/com/nextroom/nextRoomServer/util/inapp/AndroidPurchaseUtils.java
  src/main/resources/logback-spring.xml
  src/test/java/com/nextroom/nextRoomServer/util/CommonObjectMapperTest.java
Labels: ✨feature, 📃test, ♻️refactor

#148 Dev log level 변경
  src/main/resources/logback-spring.xml
Labels: 🔨fix
