Repository Next-Room/NextRoom-be, pull requests merged in 2024-12, with the labels that each got.

#150 [FEAT] Request, Response 로그 추가
  src/main/java/com/nextroom/nextRoomServer/config/FilterConfig.java
  src/main/java/com/nextroom/nextRoomServer/config/InterceptorConfig.java
  src/main/java/com/nextroom/nextRoomServer/filter/ContentCachingLoggingFilter.java
  src/main/java/com/nextroom/nextRoomServer/interceptor/LoggingInterceptor.java
  src/main/java/com/nextroom/nextRoomServer/security/config/SecurityConfig.java
  src/main/resources/logback-spring.xml
Labels: ✨feature, ♻️refactor

#152 [FEAT] 타이머 이미지 기능 추가
  src/main/java/com/nextroom/nextRoomServer/controller/ThemeController.java
  src/main/java/com/nextroom/nextRoomServer/domain/Theme.java
  src/main/java/com/nextroom/nextRoomServer/dto/ThemeDto.java
  src/main/java/com/nextroom/nextRoomServer/service/HintService.java
  src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java
  src/main/java/com/nextroom/nextRoomServer/util/aws/S3Component.java
Labels: ✨feature

#153 [FEAT] 타이머 이미지 기능 수정
  src/main/java/com/nextroom/nextRoomServer/controller/HintController.java
  src/main/java/com/nextroom/nextRoomServer/controller/ThemeController.java
  src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java
  src/main/java/com/nextroom/nextRoomServer/util/aws/S3Component.java
Labels: 📝documentation, 🔨fix

#154 [RELEASES] 힌트, 정답 이미지 첨부 기능 배포
  build.gradle
  src/main/java/com/nextroom/nextRoomServer/config/FilterConfig.java
  src/main/java/com/nextroom/nextRoomServer/config/InterceptorConfig.java
  src/main/java/com/nextroom/nextRoomServer/controller/BannerController.java
  src/main/java/com/nextroom/nextRoomServer/controller/HintController.java
  src/main/java/com/nextroom/nextRoomServer/controller/PaymentController.java
  src/main/java/com/nextroom/nextRoomServer/controller/SubscriptionController.java
  src/main/java/com/nextroom/nextRoomServer/controller/ThemeController.java
  src/main/java/com/nextroom/nextRoomServer/domain/Banner.java
  src/main/java/com/nextroom/nextRoomServer/domain/Hint.java
  src/main/java/com/nextroom/nextRoomServer/domain/Shop.java
  src/main/java/com/nextroom/nextRoomServer/dto/BannerDto.java
  src/main/java/com/nextroom/nextRoomServer/dto/HintDto.java
  src/main/java/com/nextroom/nextRoomServer/dto/SubscriptionDto.java
  src/main/java/com/nextroom/nextRoomServer/dto/ThemeDto.java
  src/main/java/com/nextroom/nextRoomServer/enums/NotificationType.java
  src/main/java/com/nextroom/nextRoomServer/exceptions/CustomException.java
  src/main/java/com/nextroom/nextRoomServer/exceptions/GlobalExceptionHandler.java
  src/main/java/com/nextroom/nextRoomServer/exceptions/StatusCode.java
  src/main/java/com/nextroom/nextRoomServer/filter/ContentCachingLoggingFilter.java
  src/main/java/com/nextroom/nextRoomServer/interceptor/LoggingInterceptor.java
  src/main/java/com/nextroom/nextRoomServer/repository/BannerRepository.java
  src/main/java/com/nextroom/nextRoomServer/repository/HintRepository.java
  src/main/java/com/nextroom/nextRoomServer/security/config/SecurityConfig.java
  src/main/java/com/nextroom/nextRoomServer/service/BannerService.java
  src/main/java/com/nextroom/nextRoomServer/service/HintService.java
  src/main/java/com/nextroom/nextRoomServer/service/PaymentService.java
  src/main/java/com/nextroom/nextRoomServer/service/ProductService.java
  src/main/java/com/nextroom/nextRoomServer/service/SubscriptionService.java
  src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java
  src/main/java/com/nextroom/nextRoomServer/util/Base64Decoder.java
  src/main/java/com/nextroom/nextRoomServer/util/CommonObjectMapper.java
  src/main/java/com/nextroom/nextRoomServer/util/aws/S3Component.java
  src/main/java/com/nextroom/nextRoomServer/util/aws/S3Config.java
  src/main/java/com/nextroom/nextRoomServer/util/inapp/AndroidPurchaseUtils.java
  src/main/resources/logback-spring.xml
  src/test/java/com/nextroom/nextRoomServer/util/CommonObjectMapperTest.java
Labels: ✨feature

#155 [FEAT] 구독 여부에 따른 타이머 이미지 active 상태 변경
  src/main/java/com/nextroom/nextRoomServer/domain/Shop.java
  src/main/java/com/nextroom/nextRoomServer/domain/Theme.java
  src/main/java/com/nextroom/nextRoomServer/service/SubscriptionService.java
  src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java
Labels: ✨feature

#156 [FEAT] 구독 결제 시, 이미 승인된 상품은 예외처리
  src/main/java/com/nextroom/nextRoomServer/exceptions/StatusCode.java
  src/main/java/com/nextroom/nextRoomServer/util/inapp/AndroidPurchaseUtils.java
Labels: ✨feature, 🔨fix

#157 [CHORE] ACKNOWLEDGEMENT_STATE_ACKNOWLEDGED 상수로 변경
  src/main/java/com/nextroom/nextRoomServer/util/inapp/AndroidPurchaseUtils.java
Labels: 🔧 chore

#158 [RELEASES] 구독 결제 시, acknowledgement 검증 로직 추가
  src/main/java/com/nextroom/nextRoomServer/exceptions/StatusCode.java
  src/main/java/com/nextroom/nextRoomServer/util/inapp/AndroidPurchaseUtils.java
Labels: 🔨fix
