Repository Next-Room/NextRoom-be, pull requests merged in 2024-05, with the labels that each got.

#113 [CHORE] 테스트를 위한 Token 만료 시간 수정
  src/main/java/com/nextroom/nextRoomServer/security/TokenProvider.java
Labels: 🔧 chore

#114 [CHORE] Token 만료 시간 연장
  src/main/java/com/nextroom/nextRoomServer/security/TokenProvider.java
Labels: 🔧 chore

#115 [CI/CD] CodeDeploy 환경변수 테스트
  scripts/start.sh
Labels: ⚙ ci/cd

#116 [CI/CD] CodeDeploy 환경변수 테스트
  scripts/start.sh
Labels: ⚙ ci/cd

#117 [CI/CD] CodeDeploy 환경변수 원복
  scripts/start.sh
Labels: ⚙ ci/cd

#118 [RELEASES] 회원가입 기능 배포
  .github/workflows/deploy-dev.yml
  README.md
  build.gradle
  src/main/java/com/nextroom/nextRoomServer/config/EmailConfig.java
  src/main/java/com/nextroom/nextRoomServer/config/RedisConfig.java
  src/main/java/com/nextroom/nextRoomServer/controller/MailController.java
  src/main/java/com/nextroom/nextRoomServer/domain/Hint.java
  src/main/java/com/nextroom/nextRoomServer/domain/Shop.java
  src/main/java/com/nextroom/nextRoomServer/domain/Theme.java
  src/main/java/com/nextroom/nextRoomServer/dto/AuthDto.java
  src/main/java/com/nextroom/nextRoomServer/dto/MailDto.java
  src/main/java/com/nextroom/nextRoomServer/exceptions/StatusCode.java
  src/main/java/com/nextroom/nextRoomServer/repository/RedisRepository.java
  src/main/java/com/nextroom/nextRoomServer/repository/ShopRepository.java
  src/main/java/com/nextroom/nextRoomServer/security/TokenProvider.java
  src/main/java/com/nextroom/nextRoomServer/security/config/SecurityConfig.java
  src/main/java/com/nextroom/nextRoomServer/service/AuthService.java
  src/main/java/com/nextroom/nextRoomServer/service/CustomUserDetailsService.java
  src/main/java/com/nextroom/nextRoomServer/service/MailService.java
  src/main/java/com/nextroom/nextRoomServer/util/RandomCodeGenerator.java
  src/main/java/com/nextroom/nextRoomServer/util/Timestamped.java
  src/main/java/com/nextroom/nextRoomServer/util/email/MailSender.java
  src/main/resources/templates/index.html
Labels: ✨feature

#119 F/unregister
  src/main/java/com/nextroom/nextRoomServer/controller/AuthController.java
  src/main/java/com/nextroom/nextRoomServer/domain/Shop.java
  src/main/java/com/nextroom/nextRoomServer/domain/Theme.java
  src/main/java/com/nextroom/nextRoomServer/repository/SubscriptionRepository.java
  src/main/java/com/nextroom/nextRoomServer/security/TokenProvider.java
  src/main/java/com/nextroom/nextRoomServer/security/jwt/JwtFilter.java
  src/main/java/com/nextroom/nextRoomServer/service/AuthService.java
Labels: ✨feature

#121 [FIX] Refresh Token 관리 방식 변경
  src/main/java/com/nextroom/nextRoomServer/domain/RefreshToken.java
  src/main/java/com/nextroom/nextRoomServer/repository/RefreshTokenRepository.java
  src/main/java/com/nextroom/nextRoomServer/security/SecurityUtil.java
  src/main/java/com/nextroom/nextRoomServer/security/TokenProvider.java
  src/main/java/com/nextroom/nextRoomServer/service/AuthService.java
  src/main/java/com/nextroom/nextRoomServer/service/HintService.java
  src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java
Labels: 🔨fix

#122 [RELEASES] 탈퇴 기능 & 다중 디바이스 대응 배포
  src/main/java/com/nextroom/nextRoomServer/controller/AuthController.java
  src/main/java/com/nextroom/nextRoomServer/domain/RefreshToken.java
  src/main/java/com/nextroom/nextRoomServer/domain/Shop.java
  src/main/java/com/nextroom/nextRoomServer/domain/Theme.java
  src/main/java/com/nextroom/nextRoomServer/repository/RefreshTokenRepository.java
  src/main/java/com/nextroom/nextRoomServer/repository/SubscriptionRepository.java
  src/main/java/com/nextroom/nextRoomServer/security/SecurityUtil.java
  src/main/java/com/nextroom/nextRoomServer/security/TokenProvider.java
  src/main/java/com/nextroom/nextRoomServer/security/jwt/JwtFilter.java
  src/main/java/com/nextroom/nextRoomServer/service/AuthService.java
  src/main/java/com/nextroom/nextRoomServer/service/HintService.java
  src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java
Labels: ✨feature, 🔨fix
