Repository Next-Room/NextRoom-be, pull requests merged in 2024-09, with the labels that each got.

#134 [RELEASES] 구독 기능 배포
  .github/workflows/deploy-dev.yml
  src/main/java/com/nextroom/nextRoomServer/controller/AuthController.java
  src/main/java/com/nextroom/nextRoomServer/controller/PaymentController.java
  src/main/java/com/nextroom/nextRoomServer/controller/ProductController.java
  src/main/java/com/nextroom/nextRoomServer/controller/SubscriptionController.java
  src/main/java/com/nextroom/nextRoomServer/controller/TestController.java
  src/main/java/com/nextroom/nextRoomServer/domain/Payment.java
  src/main/java/com/nextroom/nextRoomServer/domain/Product.java
  src/main/java/com/nextroom/nextRoomServer/domain/Shop.java
  src/main/java/com/nextroom/nextRoomServer/domain/Subscription.java
  src/main/java/com/nextroom/nextRoomServer/dto/PaymentDto.java
  src/main/java/com/nextroom/nextRoomServer/dto/ProductDto.java
  src/main/java/com/nextroom/nextRoomServer/dto/SubscriptionDto.java
  src/main/java/com/nextroom/nextRoomServer/enums/EnumModel.java
  src/main/java/com/nextroom/nextRoomServer/enums/NotificationType.java
  src/main/java/com/nextroom/nextRoomServer/enums/SubscriptionPlan.java
  src/main/java/com/nextroom/nextRoomServer/enums/SubscriptionState.java
  src/main/java/com/nextroom/nextRoomServer/enums/SubscriptionStatus.java
  src/main/java/com/nextroom/nextRoomServer/enums/UserStatus.java
  src/main/java/com/nextroom/nextRoomServer/exceptions/StatusCode.java
  src/main/java/com/nextroom/nextRoomServer/repository/PaymentRepository.java
  src/main/java/com/nextroom/nextRoomServer/repository/ProductRepository.java
  src/main/java/com/nextroom/nextRoomServer/repository/SubscriptionRepository.java
  src/main/java/com/nextroom/nextRoomServer/service/AuthService.java
  src/main/java/com/nextroom/nextRoomServer/service/ProductService.java
  src/main/java/com/nextroom/nextRoomServer/service/SubscriptionService.java
  src/main/java/com/nextroom/nextRoomServer/util/Base64Decoder.java
  src/main/java/com/nextroom/nextRoomServer/util/Timestamped.java
  src/main/java/com/nextroom/nextRoomServer/util/inapp/AndroidPurchaseUtils.java
  src/test/java/com/nextroom/nextRoomServer/controller/AuthControllerTest.java
  src/test/java/com/nextroom/nextRoomServer/service/PaymentTest.java
  src/test/java/com/nextroom/nextRoomServer/service/ThemeServiceTest.java
Labels: 🐞bug, 📝documentation, ✨feature, ⚙ ci/cd

#138 [CHORE] 테마 등록 API Response 변경
  src/main/java/com/nextroom/nextRoomServer/controller/ThemeController.java
  src/main/java/com/nextroom/nextRoomServer/dto/ThemeDto.java
  src/main/java/com/nextroom/nextRoomServer/service/ThemeService.java
Labels: 🔧 chore

#139 [FEAT] 배너, 구독 요금제 조회 기능 추가
  src/main/java/com/nextroom/nextRoomServer/controller/BannerController.java
  src/main/java/com/nextroom/nextRoomServer/controller/SubscriptionController.java
  src/main/java/com/nextroom/nextRoomServer/domain/Banner.java
  src/main/java/com/nextroom/nextRoomServer/dto/BannerDto.java
  src/main/java/com/nextroom/nextRoomServer/dto/SubscriptionDto.java
  src/main/java/com/nextroom/nextRoomServer/repository/BannerRepository.java
  src/main/java/com/nextroom/nextRoomServer/security/config/SecurityConfig.java
  src/main/java/com/nextroom/nextRoomServer/service/BannerService.java
  src/main/java/com/nextroom/nextRoomServer/service/SubscriptionService.java
Labels: ✨feature, ♻️refactor

#136 [FEAT] 이미지 첨부 기능 추가
  build.gradle
  src/main/java/com/nextroom/nextRoomServer/controller/HintController.java
  src/main/java/com/nextroom/nextRoomServer/domain/Hint.java
  src/main/java/com/nextroom/nextRoomServer/dto/HintDto.java
  src/main/java/com/nextroom/nextRoomServer/exceptions/StatusCode.java
  src/main/java/com/nextroom/nextRoomServer/repository/HintRepository.java
  src/main/java/com/nextroom/nextRoomServer/service/HintService.java
  src/main/java/com/nextroom/nextRoomServer/util/aws/S3Component.java
  src/main/java/com/nextroom/nextRoomServer/util/aws/S3Config.java
Labels: 📝documentation, ✨feature, ♻️refactor
